name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] # Chỉ chạy khi push lên nhánh main

# Cấp quyền cho workflow để ghi lên GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Đảm bảo chỉ có một lần deploy chạy tại một thời điểm
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Chỉ cần một phiên bản ổn định để deploy

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Chạy lệnh build đã cấu hình trong package.json

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Tải lên nội dung của thư mục 'dist'
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
